USE [master]
GO

/****** Object:  Database [nikit]    Script Date: 23.04.2019 10:50:43 ******/
CREATE DATABASE [nikit]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'nikit', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\nikit.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'nikit_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\nikit_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [nikit] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [nikit].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [nikit] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [nikit] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [nikit] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [nikit] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [nikit] SET ARITHABORT OFF 
GO

ALTER DATABASE [nikit] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [nikit] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [nikit] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [nikit] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [nikit] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [nikit] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [nikit] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [nikit] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [nikit] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [nikit] SET  DISABLE_BROKER 
GO

ALTER DATABASE [nikit] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [nikit] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [nikit] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [nikit] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [nikit] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [nikit] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [nikit] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [nikit] SET RECOVERY FULL 
GO

ALTER DATABASE [nikit] SET  MULTI_USER 
GO

ALTER DATABASE [nikit] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [nikit] SET DB_CHAINING OFF 
GO

ALTER DATABASE [nikit] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [nikit] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [nikit] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [nikit] SET QUERY_STORE = OFF
GO

ALTER DATABASE [nikit] SET  READ_WRITE 
GO

