//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public System.DateTime RentTime { get; set; }
        public int Costs { get; set; }
    }
}
