//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainEntities : DbContext
    {
        public MainEntities()
            : base("name=MainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rigths> Rigths { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Актеры> Актеры { get; set; }
        public virtual DbSet<Актеры_в_фильме> Актеры_в_фильме { get; set; }
        public virtual DbSet<Персонажи> Персонажи { get; set; }
        public virtual DbSet<Персонажи_в_фильме> Персонажи_в_фильме { get; set; }
        public virtual DbSet<Режиссеры> Режиссеры { get; set; }
        public virtual DbSet<Студии> Студии { get; set; }
        public virtual DbSet<Фильмы> Фильмы { get; set; }
        public virtual DbSet<Pocket> Pocket { get; set; }
    }
}
