//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainEntities : DbContext
    {
        public MainEntities()
            : base("name=MainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Defects> Defects { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<ModelTypes> ModelTypes { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Pocket> Pocket { get; set; }
        public virtual DbSet<Rides> Rides { get; set; }
        public virtual DbSet<Rigths> Rigths { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
