//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website
{
    using System;
    using System.Collections.Generic;
    
    public partial class Фильмы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Фильмы()
        {
            this.Актеры_в_фильме = new HashSet<Актеры_в_фильме>();
            this.Персонажи_в_фильме = new HashSet<Персонажи_в_фильме>();
            this.Pocket = new HashSet<Pocket>();
        }
    
        public int Id { get; set; }
        public string Название { get; set; }
        public string Сюжет { get; set; }
        public System.DateTime Дата_выхода { get; set; }
        public string Страна { get; set; }
        public int Количество_серий { get; set; }
        public Nullable<int> Режиссер { get; set; }
        public Nullable<int> Студия { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Актеры_в_фильме> Актеры_в_фильме { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Персонажи_в_фильме> Персонажи_в_фильме { get; set; }
        public virtual Режиссеры Режиссеры { get; set; }
        public virtual Студии Студии { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pocket> Pocket { get; set; }
    }
}
